import MatchgateWidth.SignedCliffordAction
import MatchgateWidth.MGIMatrixTranspose
import MatchgateWidth.RankTwoGaussianHull
import MatchgateWidth.CoordinateBase

/-!
# Coordinate isotropic kernels and exact ordered covers

This file starts from the genuine signed Clifford operators. The coordinate
isotropic space is generated by the specified dual basis vectors, and its
joint kernel and an exact ordered-MGI cover are computed in actual coordinates.
-/
namespace MatchgateWidth
noncomputable section
open scoped symmDiff
variable {R : Type*} [CommRing R] {t r : ℕ}

/-- Relabel Boolean coefficients by their selected finite subset. -/
def spinorSubsetEquiv : BooleanTable t R ≃ₗ[R] SubsetSignature t R :=
  LinearEquiv.funCongrLeft R R (booleanSubsetEquiv t).symm

@[simp] theorem spinorSubsetEquiv_apply (u : BooleanTable t R) (S : Finset (Fin t)) :
    spinorSubsetEquiv u S = u ((booleanSubsetEquiv t).symm S) := rfl

/-- A mode is contracted to zero exactly when no coefficient uses that mode. -/
theorem fermionContract_eq_zero_iff (i : Fin t) (u : SubsetSignature t R) :
    fermionContract i u = 0 ↔ ∀ S, i ∈ S → u S = 0 := by
  constructor
  · intro h S hi
    have hv := congrFun h (S ∆ {i})
    simp only [fermionContract_apply, Finset.mem_symmDiff, Finset.mem_singleton,
      hi, not_true_eq_false,  and_false, or_self, ite_false,
      fermionSign_toggle_self, symmDiff_assoc, symmDiff_self, symmDiff_bot,
      Pi.zero_apply] at hv
    have he := congrArg (fun c : R => fermionSign S i * c) hv
    simpa only [← mul_assoc, fermionSign_sq, one_mul, mul_zero] using he
  · intro h
    ext S
    by_cases hi : i ∈ S
    · simp [hi]
    · simp [hi, h (S ∆ {i}) (by simp [Finset.mem_symmDiff, hi])]

/-- The coordinate isotropic subspace spanned by covectors outside `F`. -/
def coordinateIsotropic (F : Finset (Fin t)) : Submodule R (CliffordVector t R) :=
  Submodule.span R (Set.range (fun i : {i : Fin t // i ∉ F} => cliffordContractionVector i))

/-- Its genuine common kernel is exactly the tables supported on subsets of `F`. -/
theorem mem_coordinateIsotropic_kernel (F : Finset (Fin t)) (u : SubsetSignature t R) :
    u ∈ cliffordJointKernel (coordinateIsotropic F) ↔ ∀ S, ¬S ⊆ F → u S = 0 := by
  rw [mem_cliffordJointKernel]
  have heq : (∀ z ∈ coordinateIsotropic (R := R) F, signedCliffordAction z u = 0) ↔
      coordinateIsotropic F ≤ spinorAnnihilator u := Iff.rfl
  rw [heq, coordinateIsotropic, Submodule.span_le]
  simp only [Set.range_subset_iff]
  change (∀ i : {i : Fin t // i ∉ F}, signedCliffordAction (cliffordContractionVector i) u = 0) ↔ _
  simp only [signedCliffordAction_contraction, fermionContract_eq_zero_iff]
  constructor
  · intro h S hn
    obtain ⟨i, hi, hif⟩ := Finset.not_subset.mp hn
    exact h ⟨i, hif⟩ S hi
  · intro h i S hi
    exact h S (fun hs => i.property (hs hi))

/-- Every coordinate dual subspace is isotropic for the actual split pairing. -/
theorem coordinateIsotropic_isotropic (F : Finset (Fin t)) :
    CliffordIsotropic (coordinateIsotropic (R := R) F) := by
  have hz : ∀ z ∈ coordinateIsotropic (R := R) F, z.1 = 0 := by
    intro z h
    exact Submodule.span_induction (p := fun z _ => z.1 = 0)
      (by rintro _ ⟨i, rfl⟩; rfl) rfl
      (by intro z w hz hw hz' hw'; simp [hz', hw'])
      (by intro c z hz hz'; simp [hz']) h
  intro z hz' w hw'
  simp [cliffordPairing, hz z hz', hz w hw']

/-- Literal ordered coordinate inclusion of a chosen increasing mode set. -/
def coordinateKernelCover (e : Fin r ↪o Fin t) :
    Matrix (BooleanInput r) (BooleanInput t) R :=
  (pinnedOutputInclusion (reverseOutputEmbedding e).toEmbedding ∅).transpose

@[simp] theorem coordinateKernelCover_apply (e : Fin r ↪o Fin t)
    (x : BooleanInput r) (y : BooleanInput t) :
    coordinateKernelCover (R := R) e x y =
      if y = (booleanSubsetEquiv t).symm (((booleanSubsetEquiv r) x).map e.toEmbedding)
      then 1 else 0 := by
  simp [coordinateKernelCover]

/-- The coordinate inclusion is an exact ordered MGI matrix. -/
theorem coordinateKernelCover_isMatchgate (e : Fin r ↪o Fin t) :
    OrderedMatchgateMatrix (coordinateKernelCover (R := R) e) :=
  (pinnedOutputInclusion_orderedMatchgate (reverseOutputEmbedding e).toEmbedding
    (reverseOutputEmbedding e).strictMono ∅).transpose

variable {K : Type*} [Field K]

/-- Coefficient support of the span of distinct coordinate rows. -/
theorem mem_coordinateBase_rowSpace {D B : Type*} [Fintype D] [Fintype B]
    (code : D → B) (hc : Function.Injective code) (u : B → K) :
    u ∈ Submodule.span K (Set.range (coordinateBase (K := K) code).row) ↔
      ∀ y, y ∉ Set.range code → u y = 0 := by
  classical
  rw [← range_vecMulLinear]
  constructor
  · rintro ⟨v, rfl⟩ y hy
    simp only [Matrix.vecMulLinear_apply, Matrix.vecMul, dotProduct, coordinateBase]
    apply Finset.sum_eq_zero
    intro x _
    rw [ite_eq_right (fun h => hy ⟨x, h.symm⟩), mul_zero]
  · intro h
    refine ⟨fun x => u (code x), ?_⟩
    ext y
    by_cases hy : y ∈ Set.range code
    · obtain ⟨a, rfl⟩ := hy
      simp [ Matrix.vecMul, dotProduct, coordinateBase,
        hc.eq_iff]
    · rw [h y hy]
      simp only [Matrix.vecMulLinear_apply, Matrix.vecMul, dotProduct, coordinateBase]
      apply Finset.sum_eq_zero
      intro x _
      rw [ite_eq_right (fun he => hy ⟨x, he.symm⟩), mul_zero]

/-- The code behind the exact increasing output inclusion. -/
def coordinateKernelCode (e : Fin r ↪o Fin t) (x : BooleanInput r) : BooleanInput t :=
  (booleanSubsetEquiv t).symm (((booleanSubsetEquiv r) x).map e.toEmbedding)

theorem coordinateKernelCode_injective (e : Fin r ↪o Fin t) :
    Function.Injective (coordinateKernelCode e) := by
  intro x y h
  apply (booleanSubsetEquiv r).injective
  apply Finset.map_injective e.toEmbedding
  exact (booleanSubsetEquiv t).symm.injective h

set_option backward.isDefEq.respectTransparency false in
@[simp] theorem coordinateKernelCover_eq_coordinateBase (e : Fin r ↪o Fin t) :
    coordinateKernelCover (R := K) e = coordinateBase (coordinateKernelCode e) := by
  ext x y
  simp only [coordinateKernelCover_apply, coordinateBase, coordinateKernelCode]
  split_ifs <;> simp_all

/-- The exact ordered coordinate cover has all `2^r` rows independent. -/
theorem coordinateKernelCover_rank (e : Fin r ↪o Fin t) :
    (coordinateKernelCover (R := K) e).rank = 2 ^ r := by
  rw [coordinateKernelCover_eq_coordinateBase,
    coordinateBase_rank _ (coordinateKernelCode_injective e)]
  simp [BooleanInput]

/-- The free modes, in their fixed logical output order. -/
def coordinateFreeModes (e : Fin r ↪o Fin t) : Finset (Fin t) :=
  Finset.univ.map e.toEmbedding

@[simp] theorem coordinateFreeModes_card (e : Fin r ↪o Fin t) :
    (coordinateFreeModes e).card = r := by simp [coordinateFreeModes]

theorem mem_coordinateKernelCode_range (e : Fin r ↪o Fin t) (y : BooleanInput t) :
    y ∈ Set.range (coordinateKernelCode e) ↔
      (booleanSubsetEquiv t) y ⊆ coordinateFreeModes e := by
  constructor
  · rintro ⟨x, rfl⟩
    simp only [coordinateKernelCode, Equiv.apply_symm_apply, coordinateFreeModes]
    exact Finset.map_subset_map.mpr (Finset.subset_univ _)
  · intro h
    let A : Finset (Fin r) := Finset.univ.filter (fun i => e i ∈ (booleanSubsetEquiv t) y)
    have heq : A.map e.toEmbedding = (booleanSubsetEquiv t) y := by
      ext j
      simp only [Finset.mem_map, A, Finset.mem_filter, Finset.mem_univ, true_and,
        RelEmbedding.coe_toEmbedding]
      constructor
      · rintro ⟨i, hi, rfl⟩; exact hi
      · intro hj
        obtain ⟨i, _, hi⟩ := Finset.mem_map.mp (h hj)
        change e i = j at hi
        exact ⟨i, hi.symm ▸ hj, hi⟩
    refine ⟨(booleanSubsetEquiv r).symm A, ?_⟩
    simp [coordinateKernelCode, heq]

/-- Exact equality with the genuine joint kernel, expressed in Boolean rows. -/
theorem mem_coordinateKernelCover_rowSpace (e : Fin r ↪o Fin t) (u : BooleanTable t K) :
    u ∈ orderedRowSpace (coordinateKernelCover e) ↔
      spinorSubsetEquiv u ∈ cliffordJointKernel (coordinateIsotropic (coordinateFreeModes e)) := by
  rw [orderedRowSpace, coordinateKernelCover_eq_coordinateBase,
    mem_coordinateBase_rowSpace _ (coordinateKernelCode_injective e),
    mem_coordinateIsotropic_kernel]
  constructor
  · intro h S hn
    exact h ((booleanSubsetEquiv t).symm S)
      (by simpa only [mem_coordinateKernelCode_range, Equiv.apply_symm_apply] using hn)
  · intro h y hn
    simpa using h ((booleanSubsetEquiv t) y) (by rwa [← mem_coordinateKernelCode_range])

/-- Subset-coordinate row space of the exact ordered coordinate cover. -/
theorem coordinateKernelCover_rowSpace (e : Fin r ↪o Fin t) :
    (orderedRowSpace (coordinateKernelCover (R := K) e)).map spinorSubsetEquiv.toLinearMap =
      cliffordJointKernel (coordinateIsotropic (coordinateFreeModes e)) := by
  ext u
  constructor
  · rintro ⟨v, hv, rfl⟩
    exact (mem_coordinateKernelCover_rowSpace e v).mp hv
  · intro h
    refine ⟨spinorSubsetEquiv.symm u, ?_, spinorSubsetEquiv.apply_symm_apply u⟩
    apply (mem_coordinateKernelCover_rowSpace e (spinorSubsetEquiv.symm u)).mpr
    simpa using h

/-- The computed joint kernel has precisely the source's `2^r` dimension. -/
theorem coordinateIsotropic_kernel_finrank (e : Fin r ↪o Fin t) :
    Module.finrank K (cliffordJointKernel
      (coordinateIsotropic (R := K) (coordinateFreeModes e))) = 2 ^ r := by
  rw [← coordinateKernelCover_rowSpace]
  rw [← (spinorSubsetEquiv.submoduleMap (orderedRowSpace (coordinateKernelCover (R := K) e))).finrank_eq]
  rw [orderedRowSpace, ← Matrix.rank_eq_finrank_span_row, coordinateKernelCover_rank]

/-- The source's canonical case, with a proved MGI cover and the actual kernel. -/
theorem coordinate_isotropic_kernel_cover (e : Fin r ↪o Fin t) :
    ∃ P : Matrix (BooleanInput r) (BooleanInput t) K,
      OrderedMatchgateMatrix P ∧ P.rank = 2 ^ r ∧
      (orderedRowSpace P).map spinorSubsetEquiv.toLinearMap =
        cliffordJointKernel (coordinateIsotropic (coordinateFreeModes e)) :=
  ⟨coordinateKernelCover e, coordinateKernelCover_isMatchgate e,
    coordinateKernelCover_rank e, coordinateKernelCover_rowSpace e⟩

end
end MatchgateWidth
