import MatchgateWidth.MatchgateIdentities
import MatchgateWidth.StarChartObstruction
import Mathlib.FieldTheory.IntermediateField.Adjoin.Algebra
import Mathlib.RingTheory.AlgebraicIndependent.TranscendenceBasis
import Mathlib.RingTheory.AlgebraicIndependent.Transcendental

/-!
# Transcendence-degree bounds for the matchgate identity locus

This file proves bounds for the actual subfield generated by signature values,
not a coordinate-ring dimension. Polynomial coordinates belong to the field
generated by their parameters; passage from the polynomial algebra to that
field is an algebraic fraction-field extension. The integer/rational Pfaffian
charts then give `delta s` for a single MGI signature and
`card L * delta r + delta (k*r)` for the coordinates of a sampled star.

These are identity-locus versions of the parameter bounds: the separate bridge
from planar matching signatures to MGI is not assumed or asserted here.
-/

namespace MatchgateWidth

open Algebra
open scoped IntermediateField.algebraAdjoinAdjoin

/-- The field generated by finitely many elements has transcendence degree at
most their number. The field-of-fractions step is explicit. -/
theorem trdeg_adjoin_range_le_card {F K σ : Type} [Field F] [Field K]
    [Algebra F K] [Fintype σ] (a : σ → K) :
    trdeg F (IntermediateField.adjoin F (Set.range a)) ≤ Fintype.card σ := by
  have hr : trdeg F (Algebra.adjoin F (Set.range a)) ≤ Fintype.card σ := by
    have h := trdeg_le_of_surjective (MvPolynomial.aeval (R := F) a).rangeRestrict
      (MvPolynomial.aeval (R := F) a).rangeRestrict_surjective
    rw [MvPolynomial.aeval_range] at h
    exact h.trans_eq (by simp [Cardinal.mk_fintype])
  have ht := trdeg_add_eq F (Algebra.adjoin F (Set.range a))
    (A := IntermediateField.adjoin F (Set.range a))
  rw [trdeg_eq_zero (R := Algebra.adjoin F (Set.range a)), add_zero] at ht
  exact ht ▸ hr

/-- Polynomially parameterized coordinates lie in the field generated by the
parameters, so the generated coordinate field obeys the parameter bound. -/
theorem trdeg_adjoin_polynomial_coordinates_le_card
    {F K σ τ : Type} [Field F] [Field K] [Algebra F K] [Fintype σ]
    (a : σ → K) (p : τ → MvPolynomial σ F) :
    trdeg F (IntermediateField.adjoin F (Set.range fun t => MvPolynomial.aeval a (p t))) ≤
      Fintype.card σ := by
  have hincl : IntermediateField.adjoin F
      (Set.range fun t => MvPolynomial.aeval a (p t)) ≤
      IntermediateField.adjoin F (Set.range a) := by
    apply IntermediateField.adjoin_le_iff.mpr
    rintro x ⟨t, rfl⟩
    apply IntermediateField.algebra_adjoin_le_adjoin
    rw [← MvPolynomial.aeval_range]
    exact ⟨p t, rfl⟩
  exact (trdeg_le_of_injective (IntermediateField.inclusion hincl)
    (IntermediateField.inclusion_injective hincl)).trans (trdeg_adjoin_range_le_card a)

/-- The actual subfield of the value field generated by a coordinate family. -/
abbrev coordinateField {K τ : Type} [Field K] [CharZero K] (f : τ → K) :
    IntermediateField ℚ K := IntermediateField.adjoin ℚ (Set.range f)

/-- Identity-locus version of the single-signature bound: every arity-`s`
Boolean MGI signature generates a field of transcendence degree at most
`delta s = 1 + choose s 2` over the rationals. -/
theorem BooleanMatchgateIdentities.trdeg_coordinateField_le
    {s : ℕ} {K : Type} [Field K] [CharZero K] {f : BooleanTable s K}
    (hf : BooleanMatchgateIdentities f) :
    trdeg ℚ (coordinateField f) ≤ delta s := by
  obtain ⟨pivot, a, rfl⟩ := hf.exists_pfaffianPivotChart
  have h := trdeg_adjoin_polynomial_coordinates_le_card a
    (pfaffianPivotChartPolynomial s ℚ pivot (fun _ => 0))
  have heval : (fun z => MvPolynomial.aeval a
      (pfaffianPivotChartPolynomial s ℚ pivot (fun _ => 0) z)) =
      pfaffianPivotChart pivot (fun _ => 0) a := by
    funext z
    exact eval₂_pfaffianPivotChartPolynomial (algebraMap ℚ K) pivot (fun _ => 0) a z
  rw [heval] at h
  simpa only [card_pfaffianChartParameter, coordinateField, delta] using h

noncomputable section

/-- Arbitrary finite sampler alphabets share one arity-`r` chart per label. -/
abbrev AlphabetStarChartChoice (L : Type) (k r : ℕ) :=
  (L → PfaffianChartChoice r) × PfaffianChartChoice (k * r)

/-- All continuous parameters for a sampled star: one parameter family for
each shared sampler and one family for the central arity-`k*r` signature. -/
abbrev AlphabetStarChartParameter (L : Type) (k r : ℕ) :=
  (L × PfaffianChartParameter r) ⊕ PfaffianChartParameter (k * r)

@[simp] theorem card_alphabetStarChartParameter (L : Type) [Fintype L] (k r : ℕ) :
    Fintype.card (AlphabetStarChartParameter L k r) =
      Fintype.card L * delta r + delta (k * r) := by
  simp [AlphabetStarChartParameter, delta, Nat.add_comm]

/-- The entire coordinate family sampled from a central signature using a
shared sampler of width `r` for each label of `L`. -/
def sampledAlphabetStar {L : Type} {k r : ℕ} {R : Type*} [CommRing R]
    (Q : BooleanTable (k * r) R) (g : L → BooleanTable r R) : (Fin k → L) → R :=
  fun z => starContract (fun x => Q (flattenBooleanBlocks x)) (fun i => g (z i))

/-- The sampled star with all samplers and its center in fixed pivot charts. -/
def sampledAlphabetChartStar {L : Type} {k r : ℕ} {R : Type*} [CommRing R]
    (c : AlphabetStarChartChoice L k r) (a : AlphabetStarChartParameter L k r → R) :
    (Fin k → L) → R :=
  sampledAlphabetStar
    (pfaffianPivotChart c.2.1 c.2.2 (fun t => a (.inr t)))
    (fun l => pfaffianPivotChart (c.1 l).1 (c.1 l).2 (fun t => a (.inl (l, t))))

/-- Polynomial naturality for the full sampled contraction. -/
theorem sampledAlphabetChartStar_map {L : Type} {k r : ℕ} {R S : Type*}
    [CommRing R] [CommRing S] (f : R →+* S)
    (c : AlphabetStarChartChoice L k r) (a : AlphabetStarChartParameter L k r → R)
    (z : Fin k → L) :
    f (sampledAlphabetChartStar c a z) =
      sampledAlphabetChartStar c (fun t => f (a t)) z := by
  classical
  simp only [sampledAlphabetChartStar, sampledAlphabetStar, starContract,
    map_sum, map_mul, map_prod, pfaffianPivotChart_map]

/-- Actual rational coordinate polynomials for any finite sampler alphabet. -/
def sampledAlphabetChartStarPolynomial {L : Type} {k r : ℕ}
    (c : AlphabetStarChartChoice L k r) (z : Fin k → L) :
    MvPolynomial (AlphabetStarChartParameter L k r) ℚ :=
  sampledAlphabetChartStar c MvPolynomial.X z

/-- These polynomials evaluate to the stated sampled-star coordinates. -/
theorem eval₂_sampledAlphabetChartStarPolynomial {L : Type} {k r : ℕ}
    {R : Type*} [CommRing R] (f : ℚ →+* R)
    (c : AlphabetStarChartChoice L k r) (a : AlphabetStarChartParameter L k r → R)
    (z : Fin k → L) :
    MvPolynomial.eval₂ f a (sampledAlphabetChartStarPolynomial c z) =
      sampledAlphabetChartStar c a z := by
  change (MvPolynomial.eval₂Hom f a) (sampledAlphabetChartStarPolynomial c z) = _
  unfold sampledAlphabetChartStarPolynomial
  rw [sampledAlphabetChartStar_map]
  simp

/-- Each choice of an MGI center and MGI samplers lies in one of the explicit
polynomial star charts; no compositum estimate is assumed. -/
theorem exists_sampledAlphabetChartStar_of_mgi
    {L : Type} {k r : ℕ} {K : Type*} [Field K]
    {Q : BooleanTable (k * r) K} {g : L → BooleanTable r K}
    (hQ : BooleanMatchgateIdentities Q) (hg : ∀ l, BooleanMatchgateIdentities (g l)) :
    ∃ (c : AlphabetStarChartChoice L k r) (a : AlphabetStarChartParameter L k r → K),
      sampledAlphabetStar Q g = sampledAlphabetChartStar c a := by
  classical
  choose pivot a ha using fun l => (hg l).exists_pfaffianPivotChart
  obtain ⟨pivotQ, aQ, hQa⟩ := hQ.exists_pfaffianPivotChart
  refine ⟨(fun l => (pivot l, fun _ => 0), (pivotQ, fun _ => 0)),
    Sum.elim (fun t => a t.1 t.2) aQ, ?_⟩
  simp only [sampledAlphabetChartStar, Sum.elim_inl, Sum.elim_inr, ← ha, ← hQa]

/-- Identity-locus version of the sampled-star bound for any finite sampler
alphabet `L`: the generated coordinate field has transcendence degree at most
`card L * delta r + delta (k*r)`. In particular this applies to every `q ≥ 1`.
The statement remains valid for an empty alphabet and zero arities. -/
theorem trdeg_sampledAlphabetStar_coordinateField_le
    {L : Type} [Fintype L] {k r : ℕ} {K : Type} [Field K] [CharZero K]
    {Q : BooleanTable (k * r) K} {g : L → BooleanTable r K}
    (hQ : BooleanMatchgateIdentities Q) (hg : ∀ l, BooleanMatchgateIdentities (g l)) :
    trdeg ℚ (coordinateField (sampledAlphabetStar Q g)) ≤
      (Fintype.card L * delta r + delta (k * r) : ℕ) := by
  obtain ⟨c, a, ha⟩ := exists_sampledAlphabetChartStar_of_mgi hQ hg
  have h := trdeg_adjoin_polynomial_coordinates_le_card a
    (sampledAlphabetChartStarPolynomial c)
  have heval : (fun z => MvPolynomial.aeval a (sampledAlphabetChartStarPolynomial c z)) =
      sampledAlphabetChartStar c a := by
    funext z
    exact eval₂_sampledAlphabetChartStarPolynomial (algebraMap ℚ K) c a z
  rw [heval] at h
  unfold coordinateField
  rw [ha]
  simpa only [card_alphabetStarChartParameter] using h

/-- The `q`-label form of the sampled-star bound. It holds for every `q`, and
therefore in particular under the paper's convention `q ≥ 1`. -/
theorem trdeg_sampledFinStar_coordinateField_le
    {q k r : ℕ} {K : Type} [Field K] [CharZero K]
    {Q : BooleanTable (k * r) K} {g : Fin q → BooleanTable r K}
    (hQ : BooleanMatchgateIdentities Q) (hg : ∀ l, BooleanMatchgateIdentities (g l)) :
    trdeg ℚ (coordinateField (sampledAlphabetStar Q g)) ≤
      (q * delta r + delta (k * r) : ℕ) := by
  simpa only [Fintype.card_fin] using trdeg_sampledAlphabetStar_coordinateField_le hQ hg

/-- The familiar two-sampler budget `D k r` is a specialization of the actual
field-generated transcendence-degree bound. -/
theorem trdeg_sampledBooleanStar_coordinateField_le
    {k r : ℕ} {K : Type} [Field K] [CharZero K]
    {Q : BooleanTable (k * r) K} {g : Fin 2 → BooleanTable r K}
    (hQ : BooleanMatchgateIdentities Q) (hg : ∀ l, BooleanMatchgateIdentities (g l)) :
    trdeg ℚ (coordinateField (sampledAlphabetStar Q g)) ≤ D k r := by
  simpa only [D] using trdeg_sampledFinStar_coordinateField_le hQ hg

end
end MatchgateWidth
