import MatchgateWidth.TranscendentalObstruction
import MatchgateWidth.ControlledRanksProposition
import MatchgateWidth.ExactMatchgateBounds
import MatchgateWidth.TwoCenterGadget

/-! # Proposition 8.4: the closed-form companion over its exact generated field -/
namespace MatchgateWidth
noncomputable section
open scoped Classical

/-- The source's precise field `Q(f_k^tr(z) : z in {0,1}^k)`, inside `C`. -/
abbrev transcendentalCompanionField (k : ℕ) : IntermediateField ℚ ℂ :=
  coordinateField (transcendentalTable k)

/-- The same exact prime-exponential table, now with its generated field as codomain. -/
def transcendentalCompanionTable (k : ℕ) : BooleanTable k (transcendentalCompanionField k) :=
  fun z => ⟨transcendentalTable k z,
    IntermediateField.subset_adjoin _ _ (Set.mem_range_self z)⟩

@[simp] theorem transcendentalCompanionTable_coe (k : ℕ) (z : BooleanInput k) :
    (transcendentalCompanionTable k z : ℂ) = transcendentalTable k z := rfl

theorem transcendentalCompanionTable_ne_zero (k : ℕ) (z : BooleanInput k) :
    transcendentalCompanionTable k z ≠ 0 := by
  intro h
  exact transcendentalTable_ne_zero k z (congrArg Subtype.val h)

theorem transcendentalCompanionTable_algebraicIndependent (k : ℕ) :
    AlgebraicIndependent ℚ (transcendentalCompanionTable k) :=
  (transcendentalTable_algebraicIndependent k).of_comp (transcendentalCompanionField k).val

theorem transcendentalCompanionTable_flattening_rank (k : ℕ) (hk : 2 ≤ k) :
    ∀ i : Fin k, (oneVsRestFlattening (transcendentalCompanionTable k) i).rank = 2 :=
  algebraicIndependent_table_all_flattenings_rank_two hk _
    (transcendentalCompanionTable_algebraicIndependent k)

/-- The literal common-base right transform of the companion's controlled
principal-Pfaffian preimage, constructed over its exact generated field. -/
def transcendentalCompanionRightTensor (k : ℕ) (j : Fin k) :
    (ControlledQutritPort k → Fin 3) → transcendentalCompanionField k :=
  rightTransform (controlledCoordinateBase k)
    (controlledPhysicalSignature (booleanSubsetTable (transcendentalCompanionTable k))
      (fun _ => transcendentalCompanionTable_ne_zero k _) j)

theorem transcendentalCompanionRightTensor_eq (k : ℕ) (j : Fin k) :
    transcendentalCompanionRightTensor k j = controlledQutrit (transcendentalCompanionTable k) j :=
  controlledPhysicalSignature_boolean_rightTransform _
    (transcendentalCompanionTable_ne_zero k) j

/-- Proposition 8.4's finite valid width-`2^k+3` field-preserving presentation,
exact coordinate restriction, complete primitive ranks, both-side essentiality,
and the two-center ordered planar coupling conclusion. All graph weights lie in
exactly the field generated by the displayed prime-exponential table. -/
theorem transcendental_companion_presentation_proposition (k : ℕ) (hk : 2 ≤ k)
    (j : Fin k) :
    let K := transcendentalCompanionField k
    let f := transcendentalCompanionTable k
    let R := transcendentalCompanionRightTensor k j
    Fintype.card ControlledLanguageLabel = 5 ∧
    (controlledCoordinateBase (K := K) k).rank = 3 ∧
    (controlledPhysicalOrder k).length = (k + 2) * (2 ^ k + 3) ∧
    (∀ l : ControlledLanguageLabel,
      ∃ (v e : ℕ) (G : WeightedGraph (Fin v) (Fin e) ℂ)
        (ext : Fin (controlledLanguageBooleanArity k l) → Fin v),
        Nonempty (PlanarDrawing G ext) ∧
        (∀ a, G.weight a ∈ K) ∧
        ∀ y, deletionSignature G ext y =
          (controlledLanguageBoolean f (transcendentalCompanionTable_ne_zero k) j l
            ((booleanWordEquiv _).symm y) : ℂ)) ∧
    R = controlledQutrit f j ∧
    (∀ a, ((∃ i, a (Sum.inr i) = 1) ∨
      (a (Sum.inl 0) = 2 ∨ a (Sum.inl 1) = 2)) → R a = 0) ∧
    (∀ x, R (controlledQutritAssignment 0 0 x) = f x ∧
      R (controlledQutritAssignment 1 1 x) = hardControlWeight (x j) * f x ∧
      R (controlledQutritAssignment 0 1 x) = 0 ∧
      R (controlledQutritAssignment 1 0 x) = 0) ∧
    (∀ l p, (portFlatten (controlledLanguageTensor f j l) p).rank =
      controlledLanguagePortRank l) ∧
    (∀ l : Fin 2, columnSupport (portFlatten R (Sum.inl l)) =
      Submodule.span K ({Pi.single 0 (1 : K), Pi.single 1 (1 : K)} : Set (Fin 3 → K))) ∧
    (∀ i : Fin k, columnSupport (portFlatten R (Sum.inr i)) =
      Submodule.span K ({Pi.single 0 (1 : K), Pi.single 2 (1 : K)} : Set (Fin 3 → K))) ∧
    ((⨆ r : Fin 3, columnSupport (portFlatten (qutritPinTensor (K := K) r) 0)) ⊔
      (⨆ l : Fin 2, columnSupport (portFlatten (qutritNeqTensor (K := K)) l)) = ⊤) ∧
    (⨆ p : ControlledQutritPort k, columnSupport (portFlatten R p)) = ⊤ ∧
    Nonempty (TwoCenterNetworkPlanarCertificate k) ∧
    (∀ z y, twoCenterValue f (transcendentalCompanionTable_ne_zero k) j z y =
      hardTableExtension f z * hardTableExtension f y *
        (hardWeightExtension j z + hardWeightExtension j y)) ∧
    Matrix.rank (twoCenterValue f (transcendentalCompanionTable_ne_zero k) j :
      Matrix (Fin k → Fin 3) (Fin k → Fin 3) K) = 2 ∧
    ¬ ∃ U V : (Fin k → Fin 3) → K, ∀ z y,
      twoCenterValue f (transcendentalCompanionTable_ne_zero k) j z y = U z * V y := by
  dsimp only
  rw [transcendentalCompanionRightTensor_eq]
  let f := transcendentalCompanionTable k
  have hf := transcendentalCompanionTable_ne_zero k
  have hrank := transcendentalCompanionTable_flattening_rank k hk
  refine ⟨controlledLanguageLabel_card, controlledCoordinateBase_rank k,
    controlledPhysicalOrder_length k, ?_, rfl, ?_, ?_,
    controlledLanguageTensor_port_ranks f hf j hrank, ?_, ?_,
    qutritPins_and_neq_support_essential,
    controlledQutrit_support_essential f j (hf _) (hrank j),
    twoCenter_coupling_proposition f hf j⟩
  · intro l
    exact field_preserving_matchgate_realization (transcendentalCompanionField k).toSubfield
      (controlledLanguageBoolean f hf j l) (controlledLanguageBoolean_mgi f hf j l)
  · intro a h
    rcases h with ⟨i, hi⟩ | (h₀ | h₁)
    · have hbad : ¬ ∀ i, a (Sum.inr i) ≠ 1 := fun h => h i hi
      simp [controlledQutrit, hbad]
    · simp [controlledQutrit, h₀]
    · simp [controlledQutrit, h₁]
  · intro x
    exact ⟨controlledQutrit_00 f j x, controlledQutrit_11 f j x,
      controlledQutrit_01 f j x, controlledQutrit_10 f j x⟩
  · intro l
    rw [controlledQutrit_link_support f j (hf _) l, qutritCoordinatePlane_two_eq_span]
  · intro i
    rw [controlledQutrit_hard_support f j i (hrank i), qutritCoordinatePlane_one_eq_span]


/-- The full rank/support/coupling conclusions over the ambient complex field,
so no unproved field-extension preservation is implicit in Proposition 8.4. -/
theorem transcendental_companion_complex_ranks (k : ℕ) (hk : 2 ≤ k) (j : Fin k) :
    let f := transcendentalTable k
    (∀ l p, (portFlatten (controlledLanguageTensor f j l) p).rank =
      controlledLanguagePortRank l) ∧
    (∀ l : Fin 2, columnSupport (portFlatten (controlledQutrit f j) (Sum.inl l)) =
      Submodule.span ℂ ({Pi.single 0 (1 : ℂ), Pi.single 1 (1 : ℂ)} : Set (Fin 3 → ℂ))) ∧
    (∀ i : Fin k, columnSupport (portFlatten (controlledQutrit f j) (Sum.inr i)) =
      Submodule.span ℂ ({Pi.single 0 (1 : ℂ), Pi.single 2 (1 : ℂ)} : Set (Fin 3 → ℂ))) ∧
    ((⨆ r : Fin 3, columnSupport (portFlatten (qutritPinTensor (K := ℂ) r) 0)) ⊔
      (⨆ l : Fin 2, columnSupport (portFlatten (qutritNeqTensor (K := ℂ)) l)) = ⊤) ∧
    (⨆ p : ControlledQutritPort k, columnSupport (portFlatten (controlledQutrit f j) p)) = ⊤ ∧
    Nonempty (TwoCenterNetworkPlanarCertificate k) ∧
    (∀ z y, twoCenterValue f (transcendentalTable_ne_zero k) j z y =
      hardTableExtension f z * hardTableExtension f y *
        (hardWeightExtension j z + hardWeightExtension j y)) ∧
    Matrix.rank (twoCenterValue f (transcendentalTable_ne_zero k) j :
      Matrix (Fin k → Fin 3) (Fin k → Fin 3) ℂ) = 2 ∧
    ¬ ∃ U V : (Fin k → Fin 3) → ℂ, ∀ z y,
      twoCenterValue f (transcendentalTable_ne_zero k) j z y = U z * V y := by
  dsimp only
  let f := transcendentalTable k
  have hf := transcendentalTable_ne_zero k
  have hrank := transcendentalTable_all_flattenings_rank_two k hk
  refine ⟨controlledLanguageTensor_port_ranks f hf j hrank, ?_, ?_,
    qutritPins_and_neq_support_essential,
    controlledQutrit_support_essential f j (hf _) (hrank j),
    twoCenter_coupling_proposition f hf j⟩
  · intro l
    rw [controlledQutrit_link_support f j (hf _) l, qutritCoordinatePlane_two_eq_span]
  · intro i
    rw [controlledQutrit_hard_support f j i (hrank i), qutritCoordinatePlane_one_eq_span]

end
end MatchgateWidth
